/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_cs_libprotnmr_cgal_spherical_SphericalCgal */

#ifndef _Included_edu_duke_cs_libprotnmr_cgal_spherical_SphericalCgal
#define _Included_edu_duke_cs_libprotnmr_cgal_spherical_SphericalCgal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_SphericalCgal
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_SphericalCgal_nativeCleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_duke_cs_libprotnmr_cgal_spherical_Circle3 */

#ifndef _Included_edu_duke_cs_libprotnmr_cgal_spherical_Circle3
#define _Included_edu_duke_cs_libprotnmr_cgal_spherical_Circle3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_Circle3
 * Method:    cleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_Circle3_cleanup
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_Circle3
 * Method:    getCenter
 * Signature: ()Ledu/duke/cs/libprotnmr/geom/Vector3;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_Circle3_getCenter
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_Circle3
 * Method:    getSquaredRadius
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_Circle3_getSquaredRadius
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_Circle3
 * Method:    getNormal
 * Signature: ()Ledu/duke/cs/libprotnmr/geom/Vector3;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_Circle3_getNormal
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_Circle3
 * Method:    init
 * Signature: (Ledu/duke/cs/libprotnmr/geom/Vector3;Ledu/duke/cs/libprotnmr/geom/Vector3;Ledu/duke/cs/libprotnmr/geom/Vector3;)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_Circle3_init
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3 */

#ifndef _Included_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
#define _Included_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
 * Method:    cleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3_cleanup
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
 * Method:    getSupportingCircle
 * Signature: ()Ledu/duke/cs/libprotnmr/cgal/spherical/Circle3;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3_getSupportingCircle
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
 * Method:    getSource
 * Signature: ()Ledu/duke/cs/libprotnmr/geom/Vector3;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3_getSource
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
 * Method:    getTarget
 * Signature: ()Ledu/duke/cs/libprotnmr/geom/Vector3;
 */
JNIEXPORT jobject JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3_getTarget
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3
 * Method:    init
 * Signature: (Ledu/duke/cs/libprotnmr/cgal/spherical/Circle3;Ledu/duke/cs/libprotnmr/geom/Vector3;Ledu/duke/cs/libprotnmr/geom/Vector3;)V
 */
JNIEXPORT void JNICALL Java_edu_duke_cs_libprotnmr_cgal_spherical_CircularArc3_init
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
